# Generated by Django 4.0.6 on 2022-08-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='input',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.datainterface'),
        ),
    ]
