# Generated by Django 4.0.6 on 2022-08-10 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('projects', '0002_add_pipeline_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='projects', through='projects.Collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
