# Generated by Django 4.0.6 on 2022-08-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_data_interface_sql_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('r', 'R')], default='python', max_length=56),
            preserve_default=False,
        ),
    ]
