# Generated by Django 4.0.6 on 2022-10-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_language_to_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='projects.pipeline')),
            ],
        ),
    ]
