# Generated by Django 4.0.6 on 2022-10-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_language_to_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('time_zone', models.CharField(choices=[('UTC', 'UTC'), ('AST', 'AST'), ('MST', 'MST'), ('PST', 'PST')], max_length=56)),
                ('frequency', models.CharField(choices=[('no_repeat', 'Does not repeat'), ('every', 'Every...'), ('every_other', 'Every other...'), ('hourly', 'Hourly...'), ('daily', 'Daily...'), ('weekly', 'Weekly...'), ('montly', 'Montly...'), ('anually', 'Anually...')], max_length=56)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, choices=[('seconds', 'Second(s)'), ('minutes', 'Minute(s)'), ('hours', 'Hour(s)'), ('days', 'Day(s)'), ('weeks', 'Week(s)'), ('months', 'Month(s)'), ('years', 'Year(s)')], max_length=56, null=True)),
                ('published', models.BooleanField(default=False)),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='projects.pipeline')),
            ],
        ),
    ]
