# Generated by Django 4.0.6 on 2022-10-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('projects', '0006_add_pipelineschedule_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineschedule',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
