# Generated by Django 4.0.6 on 2022-10-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_celery_schedule_to_pipeline_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.pipeline'),
        ),
    ]
