# Generated by Django 4.0.6 on 2022-11-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_django_simple_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldatainterface',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldatainterface',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicalpipeline',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpipeline',
            name='input',
        ),
        migrations.RemoveField(
            model_name='historicalpipeline',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicalpipelineschedule',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpipelineschedule',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='historicalpipelineschedule',
            name='task',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstep',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstep',
            name='pipeline',
        ),
        migrations.AlterField(
            model_name='pipelineschedule',
            name='interval',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipelineschedule',
            name='unit',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds')], default='days', max_length=56),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalCollaborator',
        ),
        migrations.DeleteModel(
            name='HistoricalDataInterface',
        ),
        migrations.DeleteModel(
            name='HistoricalPipeline',
        ),
        migrations.DeleteModel(
            name='HistoricalPipelineSchedule',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
        migrations.DeleteModel(
            name='HistoricalStep',
        ),
    ]
