# Generated by Django 4.0.6 on 2022-11-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_historicalpipelineschedule_time_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineschedule',
            name='pipeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='projects.pipeline'),
        ),
    ]
